import { StrategyInterface } from "@/types/strategy";

export const dummyStrategies: StrategyInterface[] = [
    {
        id: "volume",
        name: "Aster Points Maximizer",
        strategy: "Earn Aster Rh Points",
        apy: "5.5%",
        currentTVL: 11317930.10,
        maxCapacity: 26000000,
        network: "Binance",
        status: "NEW",
        capacity: 43.5, // Approximate percentage (currentTVL / maxCapacity * 100)
        maxCap: 26000000, // Same as maxCapacity
        // --- Other Plausible Demo Metrics ---
        highestApy: 6.1, // Slightly higher "peak" APY/Point Rate for demo appeal
        dailyDrawdown: 0.15, // % - Plausible small daily fluctuation/cost percentage for demo
        volume: 52500000, // Example 24h Volume generated by the bot
        chain: "BSC", // Blockchain network
        collateral: "USDT", // Asset used for trading
        leverage: 1, // No leverage used inherently by this bot
        riskLevel: 3, // Medium-High risk due to fees/slippage, despite simple logic
        liquidationThreshold: 0, // Not applicable / No liquidation risk from leverage
        age: "90 Days", // Example age
        createdAt: "2024-01-27T00:00:00Z", // Example creation date
        protocols: ["AsterDex API"], // Protocol interacted with
        performanceFee: 0, // % - Assuming no performance fee for this type
        withdrawalFee: 0.1, // % - Small withdrawal fee example
        earlyExitPenalty: false, // No penalty
        isActive: true // Assuming active for demo

    },
    {
        id: "normal_grid",
        name: "Normal Grid",
        strategy: "Uses equal price steps",
        apy: "13.85%",
        currentTVL: 738342.05,
        maxCapacity: 1000000,
        network: "Binance",
        status: "HOT",
        // --- Calculated/Derived ---
        capacity: 73.8, // Approximate percentage (currentTVL / maxCapacity * 100)
        maxCap: 1000000, // Same as maxCapacity
        // --- Other Plausible Demo Metrics ---
        highestApy: 15.2, // % - Slightly higher peak APY for demo
        dailyDrawdown: 0.45, // % - Plausible daily fluctuation if price moves within the grid against open orders
        volume: 650000, // Example 24h Volume generated by grid trades
        chain: "BSC", // Blockchain network
        collateral: "USDT", // Asset used for trading
        leverage: 1, // No leverage used inherently
        riskLevel: 2, // Medium risk - Profits in ranges, but risks breakout
        liquidationThreshold: 0, // Not applicable / No liquidation risk from leverage
        age: "120 Days", // Example age
        createdAt: "2023-12-28T00:00:00Z", // Example creation date
        protocols: ["AsterDex API"], // Protocol interacted with
        performanceFee: 10, // % - Example performance fee on profit
        withdrawalFee: 0.1, // % - Small withdrawal fee example
        earlyExitPenalty: false, // No penalty
        isActive: true // Assuming active for demo
    },
    {
        id: "log_grid",
        name: "Log Grid",
        strategy: "Uses proportional price steps", // null: No sub-strategy shown
        apy: "17.33%",

        currentTVL: 548342.05,
        maxCapacity: 1000000,
        network: "Binance",
        status: "HOT",
        // --- Calculated/Derived ---
        capacity: 79.0, // Approximate percentage (currentTVL / maxCapacity * 100)
        maxCap: 500000, // Same as maxCapacity

        // --- Other Plausible Demo Metrics ---
        highestApy: 18.5, // % - Slightly higher peak APY for demo
        dailyDrawdown: 0.40, // % - Plausible daily fluctuation
        volume: 480000, // Example 24h Volume generated by grid trades
        chain: "BSC", // Blockchain network
        collateral: "USDT", // Asset used for trading
        leverage: 1, // No leverage used inherently
        riskLevel: 2, // Medium risk - Similar risks to Normal Grid
        liquidationThreshold: 0, // Not applicable / No liquidation risk from leverage
        age: "30 Days", // Example age for "NEW" status
        createdAt: "2024-03-27T00:00:00Z", // Example recent creation date
        protocols: ["AsterDex API"], // Protocol interacted with
        performanceFee: 10, // % - Example performance fee on profit
        withdrawalFee: 0.1, // % - Small withdrawal fee example
        earlyExitPenalty: false, // No penalty
        isActive: true,
    }
];
